#!/usr/bin/env bash

# Change to the script's directory
cd "$(dirname "$0")"

packages=(
  bat
  brew
  btop
  git
  intellij
  nvim
  omz
  p10k
  tldr
  tmux
  zsh
)

# WSL
if [[ -v WSL_DISTRO_NAME ]]; then
  packages+=(
      wsl
  )
fi

# Mac 
if [[ "$OSTYPE" == "darwin"* ]]; then
  packages+=(
    ghostty
  )
fi

# Function to run command with red stderr
red_stderr() {
  "$@" 2> >(while read -r line; do printf '\e[31m%s\e[0m\n' "$line" >&2; done)
}

# Stow all packages
for pkg in "${packages[@]}"; do
  echo "Stowing $pkg"
  if [[ $pkg == "wsl" ]]; then
      # wsl package needs to be stowed to /etc
      red_stderr sudo "$(which stow)" "$@" -R --target="/etc" "$pkg"
  else
      red_stderr stow "$@" -R "$pkg"
  fi
done
